### ISSUE TITLE
Small suggestions

### ISSUE THREAD

**Issue by tgulacsi** [jonathansp/guess-language#2]
1: guesslang_test.go: use table-driven tests in TestCommonLanguages:

```
func TestCommonLanguages(t *testing.T) {
    for i, want := range []struct{
        lang, text string
    } {
        {"pt", "..."},
        {"hu", "..."},
    } {
        got, err := Parse(pt)
        if err != nil {
            t.Fatalf("%d. Parse: %v", i, err)
        }
        if got.ISOcode != want.lang {
            t.Fatalf("Expected %s, got %s.", want.lang, got.ISOcode)
        }
    }
}
```
1. map returns the zero value, which is 0 for ints, so no need to check existence & set to 0, just use  
   `trigrams[content[i:end]] += 1` in createModel.
2. `createModel: return arrays.SortedKeys(trigrams)` - no need to build another slice of it.
3. arrays.In: use sorted slices and use sort.SearchStrings from the standard library.

**Comment by jonathansp** [comment]
Done. Thanks! ;)
