### ISSUE TITLE
Source of language datasets

### ISSUE THREAD

**Issue by DonaldTsang** [jonathansp/guess-language#4]
Where is the source text dataset for the Ngrams of those 94 languages? Would like to see if it is different from wooorm/franc#78 usage of UDHR, and if it is more accurate than them.

**Comment by jonathansp** [comment]
@DonaldTsang this project uses a quite old trigrams database (around 13 years old) with a few fixes for Russian.  

https://github.com/kent37/guess-language/tree/master/guess_language/trigrams

https://websvn.kde.org/branches/work/sonnet-refactoring/common/nlp/guesslanguage.cpp?view=markup

**Comment by DonaldTsang** [comment]
Mind if I ask, what text dat aset was used in those two "source projects"? It seems non-trivial to read the actual document.

**Comment by jonathansp** [comment]
@DonaldTsang both were based on the work of Maciej Ceglowski https://idlewords.com/resume.htm

Please contact the author for further information.
